"""
Utility Module.
Provides session logging and a rebranded, styled PDF Report Generator using ReportLab.
"""

import io
import os
import time
from datetime import datetime
from typing import List, Dict, Any
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib.utils import simpleSplit
from reportlab.lib import colors

class StreamlitLogHandler:
    """
    Captures runtime logs to display them dynamically in the Streamlit UI console.
    """
    def __init__(self):
        self.logs = []
        
    def info(self, msg: str):
        timestamp = datetime.now().strftime("%H:%M:%S")
        formatted_msg = f"[{timestamp}] {msg}"
        self.logs.append(formatted_msg)
        print(f"INFO: {formatted_msg}")
        
    def clear(self):
        self.logs = []
        
    def get_logs(self) -> List[str]:
        return self.logs

# Global system logger instance
sys_logger = StreamlitLogHandler()

def generate_pdf_report(
    user_queries: List[str], 
    ai_responses: List[str],
    similarity_scores: List[float],
    metrics: Dict[str, Any]
) -> bytes:
    """
    Generates a professionally-styled PDF document QA report using ReportLab.
    Returns the generated PDF as raw bytes.
    """
    buffer = io.BytesIO()
    c = canvas.Canvas(buffer, pagesize=letter)
    page_width, page_height = letter
    margin = 72  # 1-inch margins
    max_width = page_width - 2 * margin
    line_height = 15
    
    current_date = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    def draw_header_footer(canvas_obj, page_num):
        # Deep blue header banner
        canvas_obj.setFillColor(colors.HexColor("#1e3a8a"))
        canvas_obj.rect(0, page_height - 90, page_width, 90, fill=True, stroke=False)
        
        # Title text
        canvas_obj.setFillColor(colors.white)
        canvas_obj.setFont("Helvetica-Bold", 20)
        canvas_obj.drawString(margin, page_height - 42, "📄 Document QA Report")
        
        # Subtitle text
        canvas_obj.setFont("Helvetica", 9.5)
        canvas_obj.drawString(
            margin, page_height - 62,
            f"Retrieval-Augmented Generation Platform  |  Date: {current_date}"
        )
        
        # Thin footer rule
        canvas_obj.setStrokeColor(colors.HexColor("#e2e8f0"))
        canvas_obj.setLineWidth(1)
        canvas_obj.line(margin, 50, page_width - margin, 50)
        
        # Footer text
        canvas_obj.setFillColor(colors.HexColor("#64748b"))
        canvas_obj.setFont("Helvetica", 8)
        canvas_obj.drawString(margin, 36, "Generated by Document Question Answering System (Week 7)")
        canvas_obj.drawRightString(page_width - margin, 36, f"Page {page_num}")
        canvas_obj.setFillColor(colors.black)

    # Initial draw for page 1
    draw_header_footer(c, 1)
    y = page_height - 110
    page_num = 1
    
    # 1. Metrics block title
    c.setFont("Helvetica-Bold", 12)
    c.setFillColor(colors.HexColor("#1e3a8a"))
    c.drawString(margin, y, "System Configuration & Execution Metrics")
    y -= 18
    
    c.setFont("Helvetica", 10)
    c.setFillColor(colors.HexColor("#334155"))
    
    col1_x = margin
    col2_x = page_width / 2
    
    metrics_mapping = [
        ("Embedding Model", metrics.get("embedding_model", "MiniLM")),
        ("Dimension", str(metrics.get("embedding_dimension", "384"))),
        ("Chunk Size / Overlap", f"{metrics.get('chunk_size', 500)} / {metrics.get('chunk_overlap', 100)}"),
        ("Total Chunks Created", str(metrics.get("chunks_created", 0))),
        ("Vector DB Store", "FAISS"),
        ("LLM Model Engine", metrics.get("llm", "DeepSeek-R1-Groq")),
        ("Retrieval Time", f"{metrics.get('retrieval_time', 0.0):.4f}s"),
        ("Inference Time", f"{metrics.get('generation_time', 0.0):.4f}s")
    ]
    
    # Print metrics in two balanced columns
    for i, (key, value) in enumerate(metrics_mapping):
        col_x = col1_x if i % 2 == 0 else col2_x
        c.setFont("Helvetica-Bold", 9)
        c.drawString(col_x, y, f"{key}:")
        c.setFont("Helvetica", 9)
        c.drawString(col_x + 110, y, value)
        if i % 2 != 0:
            y -= 14
            
    y -= 10
    c.setStrokeColor(colors.HexColor("#e2e8f0"))
    c.line(margin, y, page_width - margin, y)
    y -= 20
    
    # 2. Section Header: Conversation log
    c.setFont("Helvetica-Bold", 12)
    c.setFillColor(colors.HexColor("#1e3a8a"))
    c.drawString(margin, y, "Q&A Session Conversation Logs")
    y -= 20
    
    for idx, (question, answer) in enumerate(zip(user_queries, ai_responses), 1):
        # Similarity score lookup
        score = similarity_scores[idx - 1] if idx - 1 < len(similarity_scores) else 0.0
        
        # Check layout constraint
        if y < 100:
            c.showPage()
            page_num += 1
            draw_header_footer(c, page_num)
            y = page_height - 110
            
        # Draw Question
        c.setFillColor(colors.HexColor("#2563eb"))
        c.setFont("Helvetica-Bold", 10)
        q_text = f"Question {idx}: {question}"
        q_lines = simpleSplit(q_text, "Helvetica-Bold", 10, max_width)
        for line in q_lines:
            if y < 100:
                c.showPage()
                page_num += 1
                draw_header_footer(c, page_num)
                y = page_height - 110
                c.setFillColor(colors.HexColor("#2563eb"))
                c.setFont("Helvetica-Bold", 10)
            c.drawString(margin, y, line)
            y -= line_height
            
        # Draw Similarity Score Badge
        if y < 100:
            c.showPage()
            page_num += 1
            draw_header_footer(c, page_num)
            y = page_height - 110
        c.setFont("Helvetica-Oblique", 8.5)
        c.setFillColor(colors.HexColor("#64748b"))
        c.drawString(margin, y, f"Context Similarity Score: {score:.4f}")
        y -= 12
        
        # Draw Answer
        c.setFillColor(colors.HexColor("#0f172a"))
        c.setFont("Helvetica", 10)
        a_text = f"Answer: {answer}"
        a_lines = simpleSplit(a_text, "Helvetica", 10, max_width)
        for line in a_lines:
            if y < 100:
                c.showPage()
                page_num += 1
                draw_header_footer(c, page_num)
                y = page_height - 110
                c.setFillColor(colors.HexColor("#0f172a"))
                c.setFont("Helvetica", 10)
            c.drawString(margin, y, line)
            y -= line_height
            
        y -= 10
        
        # Divider line
        if idx < len(user_queries):
            if y < 100:
                c.showPage()
                page_num += 1
                draw_header_footer(c, page_num)
                y = page_height - 110
            c.setStrokeColor(colors.HexColor("#f1f5f9"))
            c.line(margin, y, page_width - margin, y)
            y -= 15
            
    c.save()
    buffer.seek(0)
    return buffer.getvalue()
